### ISSUE TITLE
Show if there are any upgrades left to earn

### ISSUE THREAD

**Issue by seiyria** [seiyria/c#11]
So people know if they have them all.

**Comment by ClayTaeto** [comment]
I'm guessing #5 depends on this? 

Or should it always show the progress?

**Comment by seiyria** [comment]
Yes, I suspect they would both have the same underlying function to calculate the achievements you have. This one would show only if you have all the upgrades, ie, where it says "no upgrades available" it would instead say "you've earned all the upgrades."

For #5, it would instead be a modal dialog that lets you see every upgrade you own (including each individual level, so it's different from the debug menu and the upgrade tree). It'd just be a simple list.
