### ISSUE TITLE
Easy cheat

### ISSUE THREAD

**Issue by soyuka** [seiyria/c#17]
I've read your [gist](https://gist.github.com/seiyria/1bfd939a1d0566223228) and I just wanted to say that a full-javascript is never safe, even if functions are not available in a public scope. 

This is ofc removing all the fun but I'm able to cheat easily with something like:

```
for(var i = 0; i < 1000; i++) { document.getElementsByTagName('button')[1].click(); }
```

Thanks for the game anyway. Do you know  the [Candy Box](http://candies.aniwey.net/) ([Candy Box 2](http://candybox2.net/)) game?

**Comment by seiyria** [comment]
> I've read your gist and I just wanted to say that a full-javascript is never safe

I have said this ad infinitum; I'm not sure why people think that it will be perfectly safe despite my saying otherwise.

The cheat is built into the game intentionally.

Yes, I've played both candy box games.

**Comment by soyuka** [comment]
Thought you were saying the exact oposite. Well, that's what I understood while reading you.

> The cheat is built into the game intentionally.

Through `$window.increaseUnits(int, string)` yes, only function available through global scope.

Thanks for the nice game anyway.

**Comment by seiyria** [comment]
Written in the 4th substantial paragraph:

> It's good to note that your game, if it's client side only, can never be fully protected.

And yes, I know, that function is intentionally exposed [here](https://github.com/seiyria/c/blob/90f76ecd416b2f692453c7d2df0111996cc98ecb/src/js/functionbuilder.js#L61-L66) with the intent that people will use it.

Thanks, glad you enjoyed it.

**Comment by mtozlu** [comment]
I enjoyed the game very much. Here is my cheat to get "Upgradus Maximus" :racehorse: 
window.increaseUnits(10000000000000000000, 'Click');

**Comment by seiyria** [comment]
I should also add a cheat: If you're interested in watching the game play itself (ie, win itself), you can check out [this wiki page](https://github.com/seiyria/c/wiki/Easy-Win). It's pretty cool to watch.
